// GENERATED by scripts/sync-portfolio.mjs — do not edit by hand.
// Source: https://ghaisansyams.vercel.app/assets/index-RY1Jhdxs.js
// Synced: 2026-09-01
window.PORTFOLIO_ORIGIN = "https://ghaisansyams.vercel.app"
window.PORTFOLIO_CATEGORIES = [{"id":"all","label":"All"},{"id":"3d","label":"3D & Creative"},{"id":"games","label":"Games"},{"id":"web","label":"Web"}]
window.PORTFOLIO = [
  {
    "id": "skillvillage-erp",
    "name": "Manajemen Pesantren",
    "kind": "flagship",
    "tagline": "Whole-School ERP for an Islamic Vocational Boarding School",
    "meta": "2026 · Full-Stack · Solo",
    "color": "#16a34a",
    "description": "The system a whole school runs on, built across fourteen sprints. One student record feeds every module: enrolment and family relations, timetables and grades, RFID attendance, dormitory beds, Qur'an memorisation tracked to the individual verse, a double-entry accounting engine, laundry, procurement and asset depreciation, a read-only parent portal, a 42-KPI executive dashboard, and an event-driven notification engine. Every business rule is a pure function, so 1,876 invariants run in CI without a database — and the last sprint added the part most side projects skip: health probes, structured logging with secret redaction, verified backups, and fourteen operator pages that let an admin diagnose the system from a browser.",
    "tech": [
      "Next.js 15",
      "TypeScript",
      "Prisma 6",
      "PostgreSQL",
      "Auth.js v5",
      "Tailwind v4",
      "Radix",
      "Recharts"
    ],
    "stats": [
      {
        "label": "Prisma Models",
        "value": "226"
      },
      {
        "label": "Migrations",
        "value": "15"
      },
      {
        "label": "Tests",
        "value": "1,876"
      },
      {
        "label": "Modules",
        "value": "14"
      }
    ],
    "url": null,
    "isPrivate": true,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/projects/skillvillage-erp/executive.webp",
        "label": "Executive Dashboard",
        "blur": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAAwAwCdASoYAA8APxFysFAsJqSisAgBgCIJaQAASmfWjL2AAP7tYW2EnoDx7swr6CAAAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/skillvillage-erp/students.webp",
        "label": "Student Master Data",
        "blur": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAgCdASoYAA8APxFysFCsJqSisAgBgCIJaQAAetCiQAD+77WUkuxDsJp3hmx/QtfiQAAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/skillvillage-erp/attendance.webp",
        "label": "Attendance Engine",
        "blur": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAgCdASoYAA8APxFysFAsJqSisAgBgCIJaQAAeyAA/u+smKxE/9o1UAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/skillvillage-erp/development.webp",
        "label": "Tahfidz & Character",
        "blur": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAgCdASoYAA8APxFysFCsJqSisAgBgCIJaQAAeyAA/u+0xjv0AgAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/skillvillage-erp/finance.webp",
        "label": "Accounting Engine",
        "blur": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAgCdASoYAA8APxFysVAsJqSisAgBgCIJaQAAeyAA/u+s+Bl/qmfFGqUGoAAAAAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/skillvillage-erp/system.webp",
        "label": "Production Tools",
        "blur": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAgCdASoYAA8APxFwsFAsJiSisAgBgCIJaQAAeyAA/u+0yYHvSDfTjUUAAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/skillvillage-erp/dashboard.webp",
        "label": "Operational Dashboard",
        "blur": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAgCdASoYAA8APxFysFAsJqSisAgBgCIJaQAAeyAA/u/WeI568hp64u3gAA=="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/projects/skillvillage-erp/executive.webp",
    "blur": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAAwAwCdASoYAA8APxFysFAsJqSisAgBgCIJaQAASmfWjL2AAP7tYW2EnoDx7swr6CAAAA=="
  },
  {
    "id": "smart-wallet",
    "name": "Skill Village Wallet",
    "kind": "flagship",
    "tagline": "Student Prepaid-Wallet ERP + POS Integration",
    "meta": "2026 · Full-Stack · Solo",
    "color": "#4f7cff",
    "description": "A ledger-first prepaid-wallet ERP for an Islamic boarding school. Finance tops up student balances offline, the Skillage Mart POS charges wallets at checkout through an idempotent API (charge-before-commit with automatic reversal on failure), and parents track every rupiah in a read-only portal. Money lives in an append-only Postgres ledger moved only by atomic row-locked RPCs, with multi-tenant RLS end-to-end — plus finance dashboards, reconciliation, reports, an audit trail and an event-driven notification centre.",
    "tech": [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Supabase",
      "PostgreSQL",
      "Tailwind v4",
      "Zod",
      "Recharts"
    ],
    "stats": [
      {
        "label": "Money",
        "value": "Ledger"
      },
      {
        "label": "Migrations",
        "value": "7"
      },
      {
        "label": "Tests",
        "value": "21"
      },
      {
        "label": "Status",
        "value": "Live"
      }
    ],
    "url": "https://deposit-smart.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/projects/smart-wallet/dashboard.webp",
        "label": "Executive Dashboard",
        "blur": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JaV2AVLMU/20C8AAA/u/esihN85llVoHza9JbVcCoZrlMSAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/smart-wallet/finance.webp",
        "label": "Finance Dashboard",
        "blur": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JaQDKADBhfYAAAP7wBFETgQD5F7pekYzVoCY2gAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/smart-wallet/wallets.webp",
        "label": "Student Wallets",
        "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAABwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JaQDA3CHgClgtpMAA/u8EoDjnUBHRCIGXqKwS9HkE4c4knTgAAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/smart-wallet/transactions.webp",
        "label": "Transaction Monitor",
        "blur": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAABwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JaQDDNCHfYsghSwAA/u8Eotef5g4dt5mp96L8AAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/smart-wallet/analytics.webp",
        "label": "Spending Analytics",
        "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAwCdASoUAA0APu1kq04ppaQiMAgBMB2JYwC2yCHfZFPnEfBYgAD+7wXJeP1PhGW1ky8oVLj7qQ9oalIpEQY4P0NK4q9wBGitHITSmuHbaGhBcAA="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/projects/smart-wallet/dashboard.webp",
    "blur": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JaV2AVLMU/20C8AAA/u/esihN85llVoHza9JbVcCoZrlMSAA="
  },
  {
    "id": "flowdesk",
    "name": "KerjaanKita",
    "kind": "flagship",
    "tagline": "Multi-Tenant Project-Management SaaS",
    "meta": "2026 · Full-Stack · Solo",
    "color": "#6366f1",
    "description": "A Linear/Jira-class work platform for any industry — organizations → workspaces → projects → tasks with a fully dynamic, per-project Kanban workflow (managers rename, reorder, recolor and weight their own columns), plus a Gantt timeline, calendar, reports and analytics. Postgres RLS enforces multi-tenant and guest isolation end-to-end, fronted by a secure read-only client portal.",
    "tech": [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Supabase",
      "PostgreSQL",
      "TanStack Query",
      "dnd-kit"
    ],
    "stats": [
      {
        "label": "Tenancy",
        "value": "RLS"
      },
      {
        "label": "Migrations",
        "value": "19"
      },
      {
        "label": "Tests",
        "value": "68"
      },
      {
        "label": "Status",
        "value": "Live"
      }
    ],
    "url": "https://kerjaankita.vercel.app",
    "isPrivate": true,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/projects/flowdesk/dashboard.webp",
        "label": "Executive Dashboard",
        "blur": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAgCdASoUAA0APyV6tFGuJ6UjsAgBwCSJaQAAeyAA/u9voelOoAAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/flowdesk/board.webp",
        "label": "Kanban Board",
        "blur": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAgCdASoUAA0APyV8tFIuJ6UisAgBwCSJaQAAeyAA/u9JbOaGYAAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/flowdesk/projects.webp",
        "label": "Projects",
        "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAgCdASoUAA0APyV8tVIuJ6UisAgBwCSJZwAAetDDQAD+726B3fK7lCDZhDVZYryhGKjyjYo4AA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/flowdesk/timeline.webp",
        "label": "Workload Timeline",
        "blur": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAgCdASoUAA0APyV6tFGuJ6UisAgBwCSJaQAAeyAA/u9ugd3ogAAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/flowdesk/calendar.webp",
        "label": "Calendar",
        "blur": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAgCdASoUAA0APyV6tFGuJ6UisAgBwCSJaQAAeyAA/u9uUzEaYaAAAAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/flowdesk/analytics.webp",
        "label": "Analytics",
        "blur": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAgCdASoUAA0APyV6tFGuJ6UisAgBwCSJaQAAeyAA/u9JbYfz4v/AAAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/flowdesk/reports.webp",
        "label": "Reports",
        "blur": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAADQAgCdASoUAA0APyV6tFGuJ6UjsAgBwCSJaQAAfj4AAP7vb6HmWIAA"
      }
    ],
    "image": "https://ghaisansyams.vercel.app/projects/flowdesk/dashboard.webp",
    "blur": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAgCdASoUAA0APyV6tFGuJ6UjsAgBwCSJaQAAeyAA/u9voelOoAAA"
  },
  {
    "id": "puri-depok-mas",
    "name": "Puri Depok Mas",
    "kind": "flagship",
    "tagline": "Real-Estate Marketing Website Revamp",
    "meta": "2026 · Full-Stack · Solo",
    "color": "#e0b85c",
    "description": "A total revamp of a Depok housing estate's official website — premium navy-gold design, WhatsApp-driven lead funnels on every CTA, a live KPR mortgage simulator and a CMS-ready admin. Fully static (SSG) for speed and SEO.",
    "tech": [
      "Next.js 15",
      "TypeScript",
      "TailwindCSS",
      "Framer Motion",
      "Three.js",
      "Swiper"
    ],
    "stats": [
      {
        "label": "Rendering",
        "value": "SSG"
      },
      {
        "label": "Lead CTAs",
        "value": "WhatsApp"
      },
      {
        "label": "KPR Calc",
        "value": "Live"
      },
      {
        "label": "Status",
        "value": "Live"
      }
    ],
    "url": "https://puri-depok-mas.vercel.app",
    "isPrivate": true,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/projects/puri-depok-mas/hero.webp",
        "label": "Landing",
        "blur": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQBACdASoYAA8APu1kq04ppaQiMAgBMB2JQBOmUABshbUU3GcsVhjfYMgAAP7sQKy4Az73ZKOL5P0ZwYKdNWu8RmWgUAKQ/lGIyjvkHVueIKNGQUa4L19+UtSUWOf13iwDpbCYMGY009p6yScQi5YAAAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/puri-depok-mas/tipe-rumah.webp",
        "label": "House Types",
        "blur": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADQAwCdASoYAA8APu1krU6ppaSiMAgBMB2JQBdgBDrsBQ7W8NYKhVQA/vHO1embqL/hAv4p1jdAVZDOKKIyLrlHrmHvvP7caQuCZP8wPclSOUWO8d+yT3QdHeJ+9eVQs8uliE+Tiu9EzU2SH+Gkmd3cDOKzBpqlxaq/dPgCIm4jzHta5obbfhQzanQQAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/puri-depok-mas/villa.webp",
        "label": "Detail & Pricing",
        "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwAwCdASoYAA8APu1iqU2ppaOiMAgBMB2JQBOgBDsFbteey2jgQAD+J74BDBqmzdi4nii2GAMkvfgf2v4eZyWUNNeG5LsQsijuvl+6DU7AfS9ilX6FPx2M4nVaRwQO14HaZ2LvdI61eWXxfdDJwEQKLlERxDWQKTHAAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/puri-depok-mas/kpr.webp",
        "label": "KPR Simulator",
        "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAwCdASoYAA8APu1mqk4ppaOiMAgBMB2JQBdgDSwAZmpj8+vlJYAA/v16jcC1Luzwov4+a/WsH59Ns0AuwhkQ21vp+/taw2nna6ZowvHYaRDG964b9JKKlba8O3iFIklhFAAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/puri-depok-mas/fasilitas.webp",
        "label": "Facilities",
        "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQAwCdASoYAA8APu1iqk2ppaQiMAgBMB2JYgCsACHXYKgrPEFIJ4AA/u/CmmZunz/es19DwgdcYWaOL6DDvpHr+Biadg8K8q7bwbHtFEFBeDeM5tOfW3P9hLJrbR8TP5q7chlPeUx9ziUQ+DnZvR86C4uMqcuIjer6K+3VBGWAfYcHYSGaqnQQAAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/puri-depok-mas/testimoni.webp",
        "label": "Google Reviews",
        "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABwAwCdASoYAA8APu1iqU2ppaOiMAgBMB2JZQAAW+pBoS8Qx0AA/vHPTi7wqcMIjr6yeCzvPc0sAPcgCTnaQO4nvbhi/JkpZ/K341yMU2v2dxAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/puri-depok-mas/admin.webp",
        "label": "Admin CMS",
        "blur": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAgCdASoYAA8APu1kqU2ppaOiMAgBMB2JZwDDNDKUAAD+8GKPiuorXgFTs/YW2Pa4MgSrQgA="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/projects/puri-depok-mas/hero.webp",
    "blur": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQBACdASoYAA8APu1kq04ppaQiMAgBMB2JQBOmUABshbUU3GcsVhjfYMgAAP7sQKy4Az73ZKOL5P0ZwYKdNWu8RmWgUAKQ/lGIyjvkHVueIKNGQUa4L19+UtSUWOf13iwDpbCYMGY009p6yScQi5YAAAA="
  },
  {
    "id": "endorse",
    "name": "ENDORSE",
    "kind": "flagship",
    "tagline": "AI Marketplace for UMKM × Influencers",
    "meta": "2026 · Full-Stack · Solo",
    "color": "#8b5cf6",
    "description": "A two-sided marketplace matching small businesses with micro-influencers. A deterministic AI engine handles matchmaking, campaign optimization and ROI projections — with an optional Claude assistant on top.",
    "tech": [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "TailwindCSS",
      "Prisma",
      "SQLite"
    ],
    "stats": [
      {
        "label": "AI Engines",
        "value": "3"
      },
      {
        "label": "User Roles",
        "value": "3"
      },
      {
        "label": "Realtime",
        "value": "SSE"
      },
      {
        "label": "Status",
        "value": "Shipped"
      }
    ],
    "url": null,
    "isPrivate": true,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/projects/endorse/landing.webp",
        "label": "Landing",
        "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAwCdASoYAA8APu1kqk4ppaQiMAgBMB2JZwAAW+xHeJlSx6Z8AAD+7a46Q0e23clhh5vu5GMyzR9fyfRXWqbo9mhAAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/endorse/dashboard.webp",
        "label": "Dashboard",
        "blur": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAAAQAwCdASoYAA8APu1iqU2tJaQiMAgBoB2JaQAAetDT48wA/vCX02+HDZLJ/lw8gAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/endorse/campaigns.webp",
        "label": "Campaigns",
        "blur": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAwAgCdASoYAA8AA4BaJZwAAp1UglOKPa0RAAD+9ler5gDfqPf9ItydZQpbxZVyufsfNN82TqUOUywoAAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/endorse/matchmaking.webp",
        "label": "AI Matchmaking",
        "blur": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAgCdASoYAA8APu1iqk2ppaQiMAgBMB2JaQAAe/QAAP7wlyXHumMKwAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/endorse/marketplace.webp",
        "label": "Marketplace",
        "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoYAA8APu1yrU+pp6QiMAgBMB2JZwAAW+yV5JO5cs1/9QAA/u/SJHWIA7FRERyE4kAoEnqvfHb3tlZp1/nn0EHVOqreoXRpNbJTDZRMfgAAAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/endorse/analytics.webp",
        "label": "Analytics",
        "blur": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAgCdASoYAA8APu1iqU2tJaOjMAgBoB2JaQAAeyAA/vCtDri/0CXq2OAAAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/endorse/assistant.webp",
        "label": "AI Assistant",
        "blur": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAAAQAwCdASoYAA8APu1iqk2ppaQiMAgBMB2JaQAAetG5MAAA/vCsP/D2Azw1owAA"
      }
    ],
    "image": "https://ghaisansyams.vercel.app/projects/endorse/landing.webp",
    "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAwCdASoYAA8APu1kqk4ppaQiMAgBMB2JZwAAW+xHeJlSx6Z8AAD+7a46Q0e23clhh5vu5GMyzR9fyfRXWqbo9mhAAA=="
  },
  {
    "id": "serambi-muda",
    "name": "Serambi Muda",
    "kind": "flagship",
    "tagline": "Parenting & Young-Family SaaS Ecosystem",
    "meta": "2026 · Full-Stack · Solo",
    "color": "#22d3ee",
    "description": "A premium, minimal parenting platform — \"Parenting Made Simple and Smart.\" An eight-module ecosystem (consultation, pregnancy, classes, community, finance and more) built on a 23-model data schema.",
    "tech": [
      "Next.js 16",
      "React 19",
      "TailwindCSS",
      "Prisma",
      "Turbopack"
    ],
    "stats": [
      {
        "label": "Modules",
        "value": "8"
      },
      {
        "label": "DB Models",
        "value": "23"
      },
      {
        "label": "Design",
        "value": "Premium"
      },
      {
        "label": "Phase 1",
        "value": "Done"
      }
    ],
    "url": null,
    "isPrivate": true,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/projects/serambi-muda/landing.webp",
        "label": "Landing",
        "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAwAwCdASoYAA8APu1iqk4ppaQiMAgBMB2JZV2AAD3k7IAAAP7v9/d7AyjzzrUw2wEB58VP2yFv9oQWF1++q/+psUh9tAAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/serambi-muda/dashboard.webp",
        "label": "Dashboard",
        "blur": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAABQAwCdASoYAA8APu1iqU2ppaQiMAgBMB2JaQAAetEz9M4AAAD+8Kw1SkKHeSib/v4wEevFwAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/serambi-muda/konsultasi.webp",
        "label": "Konsultasi",
        "blur": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAAAQAwCdASoYAA8APu1kqU2ppaOiMAgBMB2JaQAAetFBSAAA/vCoujZYexNxAgAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/serambi-muda/kelas.webp",
        "label": "Kelas",
        "blur": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAgCdASoYAA8APu1kqU2ppaOiMAgBMB2JaQAAe/QAAP7wqOWhzQtJ1L/MPIAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/serambi-muda/komunitas.webp",
        "label": "Komunitas",
        "blur": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAgCdASoYAA8APu1kqU2ppaOiMAgBMB2JaQAAetCOQAD+8Ki6NmwEMEm4gQAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/serambi-muda/marketplace.webp",
        "label": "Marketplace",
        "blur": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAgCdASoYAA8APu1iqU2ppaQiMAgBMB2JaQAAetCOQAD+8Ki6NmwEMEm4gQAA"
      }
    ],
    "image": "https://ghaisansyams.vercel.app/projects/serambi-muda/landing.webp",
    "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAwAwCdASoYAA8APu1iqk4ppaQiMAgBMB2JZV2AAD3k7IAAAP7v9/d7AyjzzrUw2wEB58VP2yFv9oQWF1++q/+psUh9tAAA"
  },
  {
    "id": "eventflow-erp",
    "name": "EventFlow ERP",
    "kind": "flagship",
    "tagline": "Multi-Tenant Event Management SaaS",
    "meta": "2026 · Full-Stack · Solo",
    "color": "#3b82f6",
    "description": "A multi-tenant ERP for event organizers with strict tenant isolation, public registration and AES-256-GCM encrypted QR tickets. Phase 2 adds a permission matrix, offline PWA scanner and a public API.",
    "tech": [
      "Next.js 15",
      "NextAuth v5",
      "TypeScript",
      "Prisma",
      "SQLite",
      "Recharts"
    ],
    "stats": [
      {
        "label": "Tenancy",
        "value": "Multi"
      },
      {
        "label": "QR",
        "value": "AES-256"
      },
      {
        "label": "API",
        "value": "v1"
      },
      {
        "label": "Phases",
        "value": "2"
      }
    ],
    "url": null,
    "isPrivate": true,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/projects/eventflow/landing.webp",
        "label": "Landing",
        "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAwCdASoYAA8APu1kqU2ppaQiMAgBMB2JZwAAW+upT2cTS/0pwAD+8c/ujsaApawoCZ9ukoAAAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/eventflow/dashboard.webp",
        "label": "Dashboard",
        "blur": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAgCdASoYAA8APu1iqU2ppaOiMAgBMB2JaQAAeyAA/vC9KysNJCgA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/eventflow/events.webp",
        "label": "Events",
        "blur": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAAQAwCdASoYAA8APu1iqU2ppaOiMAgBMB2JaQDImC0HagAA/vCR2JW6HkSOieXf6AAAAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/eventflow/participants.webp",
        "label": "Participants",
        "blur": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAgCdASoYAA8APu1iqU2ppaOiMAgBMB2JaQAAeyAA/vCm0lpaAAAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/eventflow/scanner.webp",
        "label": "Check-in Scanner",
        "blur": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAwCdASoYAA8APu1iqU2ppaOiMAgBMB2JaQDKACHw3prv/u6AAP7x21M9GafvGQRxu5+IMOoOxR2gsD8kO7AA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/eventflow/reports.webp",
        "label": "Reports",
        "blur": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAwCdASoYAA8APu1kqU2ppaQiMAgBMB2JZwDImCHfwCwuz/NCkcAA/vHAuMamMtJdUzDwsiPoPr4jtDBJgAAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/eventflow/branding.webp",
        "label": "Branding",
        "blur": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAgCdASoYAA8APu1iqU2ppaQiMAgBMB2JaQAAeyAA/vC6C1/qEAAA"
      }
    ],
    "image": "https://ghaisansyams.vercel.app/projects/eventflow/landing.webp",
    "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAwCdASoYAA8APu1kqU2ppaQiMAgBMB2JZwAAW+upT2cTS/0pwAD+8c/ujsaApawoCZ9ukoAAAA=="
  },
  {
    "id": "smc-signal-pro",
    "name": "SMC Signal Pro",
    "kind": "flagship",
    "tagline": "Real-Time Trading Signal Platform",
    "meta": "2026 · Full-Stack · Solo",
    "color": "#f59e0b",
    "description": "A professional trading app running automated Smart-Money-Concept analysis (liquidity sweeps, MSS, order blocks, FVGs) on XAUUSD & BTCUSD, streaming no-repaint signals computed only on closed candles.",
    "tech": [
      "React 19",
      "Vite",
      "Node.js",
      "Express",
      "WebSocket",
      "Lightweight Charts"
    ],
    "stats": [
      {
        "label": "Markets",
        "value": "XAU/BTC"
      },
      {
        "label": "Signals",
        "value": "Realtime"
      },
      {
        "label": "Repaint",
        "value": "None"
      },
      {
        "label": "i18n",
        "value": "EN/ID"
      }
    ],
    "url": null,
    "isPrivate": true,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/projects/smc/dashboard.webp",
        "label": "Dashboard",
        "blur": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAABQAwCdASoYAA8APu1iqU2ppaQiMAgBMB2JZwCdADKK3khAAAD+78BHCsrLhVtoZJQYAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/smc/signals.webp",
        "label": "Signals",
        "blur": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAAQAwCdASoYAA8APu1iqU2tJaOiMAgBoB2JZwC7AC0HagAA/u7bLhehHXGJv8CTl3gAAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/smc/gold.webp",
        "label": "Gold · XAU",
        "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAgCdASoYAA8APu1kqU2ppaOiMAgBMB2JZQCdADLxQAD+8ADum1K9PqxwguIjqZ5YPE1lcsAAAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/smc/bitcoin.webp",
        "label": "Bitcoin",
        "blur": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAABQAwCdASoYAA8APu1iqU2ppaQiMAgBMB2JZwC06DKK3ZQegAD+8AEBlzkDS8bW+tDGAAAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/smc/backtesting.webp",
        "label": "Backtesting",
        "blur": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAgCdASoYAA8APu1iqU2ppaOiMAgBMB2JZQAAidn+AAD+8B+PY2YY26avQCegAAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/smc/settings.webp",
        "label": "Settings",
        "blur": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAgCdASoYAA8APu1iqU2tJaQiMAgBoB2JZQAAeyAA/u/IvCOtEEr1fU98R0Zd4AA="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/projects/smc/dashboard.webp",
    "blur": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAABQAwCdASoYAA8APu1iqU2ppaQiMAgBMB2JZwCdADKK3khAAAD+78BHCsrLhVtoZJQYAA=="
  },
  {
    "id": "laundry-erp",
    "name": "Skillage Laundry",
    "kind": "flagship",
    "tagline": "Boarding-School Laundry & Finance ERP",
    "meta": "2026 · Full-Stack · Solo",
    "color": "#60a5fa",
    "description": "The ERP running laundry operations for an Islamic boarding school. Monthly bills are generated from daily weigh-ins, and anything past the 12 kg the school subsidy covers is split into a separate bill charged to parents. Expenses, cash book and a cash-basis profit & loss close the loop — every report exports to one multi-sheet Excel workbook.",
    "tech": [
      "Laravel 13",
      "Blade + Alpine",
      "PostgreSQL",
      "Chart.js",
      "Vercel"
    ],
    "stats": [
      {
        "label": "Report Sheets",
        "value": "10"
      },
      {
        "label": "Billing",
        "value": "Auto-split"
      },
      {
        "label": "P&L",
        "value": "Cash basis"
      },
      {
        "label": "Status",
        "value": "In use"
      }
    ],
    "url": null,
    "isPrivate": true,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/projects/laundry-erp/dashboard.webp",
        "label": "Dashboard",
        "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABQAwCdASoYAA8APu1krU6ppaSiMAgBMB2JZwAAetE+5cJEYAD+8LmxJWH1HvI08Fei9kRCT2ONuvKhxcEvOsuI+2Cbn7ZsVgaj92kkDk7lOWAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/laundry-erp/tagihan.webp",
        "label": "Tagihan Bulanan",
        "blur": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAgCdASoYAA8APu1kqU4ppaOiMAgBMB2JZwAAetCIAAD+8LmxZAj4SMWA79tEdEu9fBCQDEL1a/EgAAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/laundry-erp/laba-rugi.webp",
        "label": "Laba Rugi",
        "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAwAwCdASoYAA8APu1kqk4ppaQiMAgBMB2JZwAAetFrPcQAAP7wqUCswNswFiKAb7CrHQGuXXEby6AE8yGFwAAWP0Mpl6fqIAA="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/laundry-erp/pengeluaran.webp",
        "label": "Pengeluaran",
        "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAgCdASoYAA8APu1kqk4ppaQiMAgBMB2JZwAAelOUAAD+8Lrh/x6Yrb5J3wW3KTfpRIk/9+QT89A7EOIAAA=="
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/laundry-erp/transaksi.webp",
        "label": "Transaksi",
        "blur": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAgCdASoYAA8APu1iqk2ppaQiMAgBMB2JZwAAelMAAAD+8LrgF0J6MpHVNC5Uslt50oaSDgiCEgGIXq1+JAAA"
      },
      {
        "src": "https://ghaisansyams.vercel.app/projects/laundry-erp/buku-kas.webp",
        "label": "Buku Kas",
        "blur": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAgCdASoYAA8APu1iqU2ppaOiMAgBMB2JaQAAeyAA/vC67f8cLTfNXEAAAA=="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/projects/laundry-erp/dashboard.webp",
    "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABQAwCdASoYAA8APu1krU6ppaSiMAgBMB2JZwAAetE+5cJEYAD+8LmxJWH1HvI08Fei9kRCT2ONuvKhxcEvOsuI+2Cbn7ZsVgaj92kkDk7lOWAA"
  },
  {
    "id": "diecast-rally",
    "name": "Diecast Rally",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "games",
    "color": "#e8402a",
    "description": "A toy car on a sun-baked playmat at golden hour: collect twelve coins as fast as you can, then race your own best time. The car is a real raycast vehicle with per-wheel suspension — it rolls on landings, washes wide when you carry too much speed into a corner, and drifts when the handbrake cuts rear grip. Ramps lift you onto platforms holding two coins you cannot reach from the ground, brick walls and dominoes scatter on contact, and a light touch of air control lets you aim a jump. One HTML file with no build step — three.js and cannon.js load straight from a CDN.",
    "tech": [
      "three.js",
      "cannon.js",
      "RaycastVehicle",
      "No build step"
    ],
    "stats": [],
    "url": "https://diecast-rally.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/diecast-rally.webp",
        "label": "Diecast Rally",
        "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBACdASoYAA8APwFqrE6rJiQiMAgBYCAJbACdEf/gPG6vTdnLnh2nAAD+zgHRewHMW2j/TgXij6R35k4RWHYC1aui2YRv5hfeDFcCGkrgSkycsCuMv0n81Aw+qlJK42jhCdy9ihgSnFQD+6cDLMcVjZkJKwX4vr5TCqYwtgAAAA=="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/diecast-rally.webp",
    "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBACdASoYAA8APwFqrE6rJiQiMAgBYCAJbACdEf/gPG6vTdnLnh2nAAD+zgHRewHMW2j/TgXij6R35k4RWHYC1aui2YRv5hfeDFcCGkrgSkycsCuMv0n81Aw+qlJK42jhCdy9ihgSnFQD+6cDLMcVjZkJKwX4vr5TCqYwtgAAAA=="
  },
  {
    "id": "sari-roti",
    "name": "Sari Roti",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "web",
    "color": "#011689",
    "description": "A corporate landing page rebuilt pixel-for-pixel from a Figma prototype, with the design read through the Figma REST API rather than eyeballed from screenshots. Every value is sourced: the type scale and six brand colours come from the node tree, product photos are cropped by each fill's own imageTransform matrix instead of object-cover, and the three marquees run at 10s linear because that is the Smart Animate duration the prototype actually declares. The curved product strip is a ring mask struck from two radii of a giant circle. 74 MB of raw Figma assets ship as 1.4 MB of WebP.",
    "tech": [
      "Next.js 16",
      "Tailwind v4",
      "Framer Motion",
      "Figma REST API"
    ],
    "stats": [],
    "url": "https://sariroti-sigma.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/sari-roti.webp",
        "label": "Sari Roti",
        "blur": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADQAwCdASoYAA4APxl0slCspqSisAgBkCMJZAAAW+f4WIFH8pj1cSAA/utzfQ9v89Z3EsxCi8cTssO/JVELUzxXxfcZ7f4LhpPs/EPOso+SScEfuUGw+YqDYa81xEoNuSfnsIgd+ajpWtioZOeLyEtEzoXids5Rdxo51ehFoksBZkvkQAA="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/sari-roti.webp",
    "blur": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADQAwCdASoYAA4APxl0slCspqSisAgBkCMJZAAAW+f4WIFH8pj1cSAA/utzfQ9v89Z3EsxCi8cTssO/JVELUzxXxfcZ7f4LhpPs/EPOso+SScEfuUGw+YqDYa81xEoNuSfnsIgd+ajpWtioZOeLyEtEzoXids5Rdxo51ehFoksBZkvkQAA="
  },
  {
    "id": "tembak-tembakan",
    "name": "Tembak Tembakan",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "games",
    "color": "#ff4655",
    "description": "A Valorant-style FPS arena in the browser — mouse-locked aim, two hitscan guns with heat-based spread and recoil, and three abilities: flashbang, dash and heal. Enemies are blocky humans whose head, torso, arms and legs are both the model and the hitbox, so headshots one-tap and limb shots bleed damage. Every round moves the fight to a different arena — sunset city, neon plaza, desert ruins, cold hangar — and every bot you drop leaves its weapon to loot when you run dry.",
    "tech": [
      "React Three Fiber",
      "Zustand",
      "Web Audio",
      "Node-verified physics"
    ],
    "stats": [],
    "url": "https://tembak-tembakan.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/tembak-tembakan.webp",
        "label": "Tembak Tembakan",
        "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABwBACdASoYAA8APulgqU2pJaQiMAgBIB0JbACdMoGv/gMTX56JuTqs7ci5CAD3oNvrKp1EUC3aMvAub+ea/uNnJ6gw0QPRAb1sZEbWwUyVgCU520Z5uHIsg7EAYnwxvVTeZapwTi2JUqGCf4qux8vascwSCbQolci8cMG2ZIL0eO3IdOAAAA=="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/tembak-tembakan.webp",
    "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABwBACdASoYAA8APulgqU2pJaQiMAgBIB0JbACdMoGv/gMTX56JuTqs7ci5CAD3oNvrKp1EUC3aMvAub+ea/uNnJ6gw0QPRAb1sZEbWwUyVgCU520Z5uHIsg7EAYnwxvVTeZapwTi2JUqGCf4qux8vascwSCbQolci8cMG2ZIL0eO3IdOAAAA=="
  },
  {
    "id": "kubika",
    "name": "KUBIKA",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "games",
    "color": "#ffd60a",
    "description": "A playable 3D Rubik's cube — drag a sticker and the layer follows your finger before snapping to 90°: scramble, race the timer and chase your best across 2×2, 3×3 and 4×4 cubes. Pure integer-math move engine verified by 61 Node tests, synthesised ratchet sounds, confetti on the solve.",
    "tech": [
      "React Three Fiber",
      "Zustand",
      "Web Audio"
    ],
    "stats": [],
    "url": "https://rubikgua.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/kubika.webp",
        "label": "KUBIKA",
        "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAwCdASoYAA8APzmIuVQvKSWjMAgB4CcJZAC7ACFsCCAR/kNM1gAA/uLz9gEL38QIMngUgSvmfulyBLs03htYYUJoiMkoNCpi4IAAAAA="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/kubika.webp",
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAwCdASoYAA8APzmIuVQvKSWjMAgB4CcJZAC7ACFsCCAR/kNM1gAA/uLz9gEL38QIMngUgSvmfulyBLs03htYYUJoiMkoNCpi4IAAAAA="
  },
  {
    "id": "raga-sakti",
    "name": "Raga Sakti",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "games",
    "color": "#38e0ff",
    "description": "Full-body motion game — the webcam scans your whole body from across the room, calibrates your proportions, then randomises one of four movement games each round: swing to smash light-cores, jump and duck under beams, match the silhouette walls, and step across energy pads.",
    "tech": [
      "MediaPipe Pose",
      "React Three Fiber",
      "GLSL",
      "Web Audio"
    ],
    "stats": [],
    "url": "https://raga-sakti.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/raga-sakti.webp",
        "label": "Raga Sakti",
        "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoYAA8APt1apkyopSOiMAgBEBuJZQAAaTjdoozTqlnP3wAA/vQt5TZn/i2lvjUx2Vb4nRJgdRn0F2hK7LxK9iAkIlKpKhWC/mIvsDT4EFv/TvlUX+gAAA=="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/raga-sakti.webp",
    "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoYAA8APt1apkyopSOiMAgBEBuJZQAAaTjdoozTqlnP3wAA/vQt5TZn/i2lvjUx2Vb4nRJgdRn0F2hK7LxK9iAkIlKpKhWC/mIvsDT4EFv/TvlUX+gAAA=="
  },
  {
    "id": "arcane-temple",
    "name": "Arcane Temple",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "games",
    "color": "#b26bff",
    "description": "Hand-cast spellcasting game — your webcam hands are the controller: open palm charges mana, a fist snap hurls homing fireballs, swipes unleash ice novas and chain lightning, and joined palms detonate the ultimate over a floating temple under siege.",
    "tech": [
      "MediaPipe",
      "React Three Fiber",
      "GLSL",
      "Web Audio"
    ],
    "stats": [],
    "url": "https://arcane-temple.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/arcane-temple.webp",
        "label": "Arcane Temple",
        "blur": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADQAwCdASoYAA0APtFUo0uoJKMhsAgBABoJQBdgA8eqRaFyVj7KZoAA/uaHkO5t5yeKLIVqU7pRn5ppnBbbkqF9y4ccaKl95cTkzvqvFXDhF9PCn3OQIUJ6OdBKbJfGfRzzTLf4l++dytQZqkOPpNfr3jW6z0hrIZNoakAA"
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/arcane-temple.webp",
    "blur": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADQAwCdASoYAA0APtFUo0uoJKMhsAgBABoJQBdgA8eqRaFyVj7KZoAA/uaHkO5t5yeKLIVqU7pRn5ppnBbbkqF9y4ccaKl95cTkzvqvFXDhF9PCn3OQIUJ6OdBKbJfGfRzzTLf4l++dytQZqkOPpNfr3jW6z0hrIZNoakAA"
  },
  {
    "id": "basket-sakti",
    "name": "Basket Sakti",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "games",
    "color": "#ff8a3d",
    "description": "Hand-tracked 3D basketball — pinch the ball with your webcam hands, swing and release to shoot: ballistic aim assist, rim physics, a hoop that slides after every make and a 60-second challenge mode.",
    "tech": [
      "MediaPipe",
      "React Three Fiber",
      "Web Audio"
    ],
    "stats": [],
    "url": "https://basket-3d.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/basket-sakti.webp",
        "label": "Basket Sakti",
        "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQBACdASoYAA8APzmGulQvKSWjMAgB4CcJZQDImCHh2p7c5nekHUqxkAD+6NpHAkSj00Uy71YZhbM/4WcuohOgAUrDSpY9Rm9TgAAA"
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/basket-sakti.webp",
    "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQBACdASoYAA8APzmGulQvKSWjMAgB4CcJZQDImCHh2p7c5nekHUqxkAD+6NpHAkSj00Uy71YZhbM/4WcuohOgAUrDSpY9Rm9TgAAA"
  },
  {
    "id": "handfield",
    "name": "HANDFIELD",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "3d",
    "color": "#7fd4ff",
    "description": "A quarter of a million GPU particles holding a shape until your hands reach into them — open palms shove the swarm aside, a pinch drags it into a swirling core, and two pinches stretch the whole field. Type anything and it reassembles into your words. No physics engine and no React: position and velocity live in float textures, so every particle is moved by a shader.",
    "tech": [
      "three.js",
      "GPGPU",
      "GLSL",
      "MediaPipe"
    ],
    "stats": [],
    "url": "https://handfield.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/handfield.jpg",
        "label": "HANDFIELD",
        "blur": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAKCAIAAAAy3EnLAAABzklEQVR42g3P3W7SUBwA8PM/57RrS2n5rGNjIwynIZqIRp2Lxot54QOYGJ/Ae1/J99B4p3EOdRlGnDIItDLEls9z6Gnp0d8b/ODo6QuENUQNSnWFKgRJIkMsGUHcUKWTTSGUiCge+ZMFD8MoBqQ3kFFSrEo2t13IZTQs4+lQzjtYDMoFcHIapVjRtE6315/wvjuglnPTvHL7zuHhk8d7u1upDQrD88vWu7eTYbNSglpt0/XcBWOitMmFC8Ucqe4/u3fw6NXL+/tlQ8VgKvigbu1kQENCJUkmb9sFR6wRn8/6nieRpFXHeX60m0/B77EIRZJSQdrQeHittK263W6C8SqOAr4eN0+4iEQUYVunW1kVWGhDpIP8n06ShKqKbhqmqYs4dv9Mv7V/XAy8JVvNGad8EXiD4GotgyOhqXhNiKFJNplhQDPfP+8NP7W+n349cYM556GMBSlmqxSp9Xp5u6ybacLYutvqnH34CEQgnDQ/f3n9/vSnv1IJZPOW/zego9HZ8THTyGXj7h7nqN0e93sXIRuYb8ROpej1frHZzDG167Y+DYaMc7h140FatwuZnJW2ABO+Wi3ZQkSLdcwwRGlzw/Mn8yWTAMslFyL8B2zi7FxAC/d0AAAAAElFTkSuQmCC"
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/handfield.jpg",
    "blur": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAKCAIAAAAy3EnLAAABzklEQVR42g3P3W7SUBwA8PM/57RrS2n5rGNjIwynIZqIRp2Lxot54QOYGJ/Ae1/J99B4p3EOdRlGnDIItDLEls9z6Gnp0d8b/ODo6QuENUQNSnWFKgRJIkMsGUHcUKWTTSGUiCge+ZMFD8MoBqQ3kFFSrEo2t13IZTQs4+lQzjtYDMoFcHIapVjRtE6315/wvjuglnPTvHL7zuHhk8d7u1upDQrD88vWu7eTYbNSglpt0/XcBWOitMmFC8Ucqe4/u3fw6NXL+/tlQ8VgKvigbu1kQENCJUkmb9sFR6wRn8/6nieRpFXHeX60m0/B77EIRZJSQdrQeHittK263W6C8SqOAr4eN0+4iEQUYVunW1kVWGhDpIP8n06ShKqKbhqmqYs4dv9Mv7V/XAy8JVvNGad8EXiD4GotgyOhqXhNiKFJNplhQDPfP+8NP7W+n349cYM556GMBSlmqxSp9Xp5u6ybacLYutvqnH34CEQgnDQ/f3n9/vSnv1IJZPOW/zego9HZ8THTyGXj7h7nqN0e93sXIRuYb8ROpej1frHZzDG167Y+DYaMc7h140FatwuZnJW2ABO+Wi3ZQkSLdcwwRGlzw/Mn8yWTAMslFyL8B2zi7FxAC/d0AAAAAElFTkSuQmCC"
  },
  {
    "id": "aether",
    "name": "Aether",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "3d",
    "color": "#58d3ff",
    "description": "A hollow shell of 3000 glowing particles steered with bare hands — move to carry it, roll your wrist to spin it, spread both palms to swell it, hold up one to five fingers to shift its hue. Pinch and hold to charge a ring, then release: the shell throws itself across the screen and springs back together, a partial charge giving a proportionally weaker pulse. Every particle is its own damped spring on the CPU, and a One-Euro filter keeps the tracking still when your hand is still without lagging when it moves. One HTML file, no build step.",
    "tech": [
      "Three.js",
      "MediaPipe Hands",
      "GLSL",
      "One-Euro Filter"
    ],
    "stats": [],
    "url": "https://ghaisansyams.github.io/orb/",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/aether.webp",
        "label": "Aether",
        "blur": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAAAwAwCdASoYAA8APulgqU2pJaQiMAgBIB0JaQAAetCcX2QAAP7wnBPtR0kcQl4AAAA="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/aether.webp",
    "blur": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAAAwAwCdASoYAA8APulgqU2pJaQiMAgBIB0JaQAAetCcX2QAAP7wnBPtR0kcQl4AAAA="
  },
  {
    "id": "monolith-3d",
    "name": "Monolith",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "3d",
    "color": "#ff7847",
    "description": "An infinite cinematic pilgrimage — scroll-flight over a procedural dune sea toward a ringed Black Sun: zero-g physics shards, a choir of monoliths whose glyphs ignite as you pass, and a dusk that drifts stranger every lap.",
    "tech": [
      "React Three Fiber",
      "Rapier Physics",
      "GLSL",
      "Web Audio"
    ],
    "stats": [],
    "url": "https://monolith-3d.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/monolith-3d.webp",
        "label": "Monolith",
        "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQBACdASoYAA8APzmGulQvKSWjMAgB4CcJQBOgP4AZWZPmKuu6Yo+amJSAAP6iZWgiQjoYpIp1PYM9zCgvk0iAEMJQ5qf4xEIZI4/zZrvawgzYsWUA10urHTIxqU+CjRq8rJAHlN01QAAA"
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/monolith-3d.webp",
    "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQBACdASoYAA8APzmGulQvKSWjMAgB4CcJQBOgP4AZWZPmKuu6Yo+amJSAAP6iZWgiQjoYpIp1PYM9zCgvk0iAEMJQ5qf4xEIZI4/zZrvawgzYsWUA10urHTIxqU+CjRq8rJAHlN01QAAA"
  },
  {
    "id": "tenaga-dalam",
    "name": "Tenaga Dalam",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "3d",
    "color": "#e8b44a",
    "description": "Webcam telekinesis — your hand becomes a golden energy hand in 3D: pinch to grab floating crystals, release to throw, swing an open palm to push them away.",
    "tech": [
      "MediaPipe",
      "React Three Fiber",
      "Web Audio"
    ],
    "stats": [],
    "url": "https://tenaga-dalam.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/tenaga-dalam.webp",
        "label": "Tenaga Dalam",
        "blur": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoYAA8APp0+mkgloyKhMAgAsBOJZQDLLCHfZR1HUeTADS4AAP766upYuzuD0NdFjHAjFMTMhY3kpbzD/BeGsBQM6YkVGQRBPGpm1EeQMNUsAnkLeOqy27raFP5eq4p8avdizKyP3T4Gezl0ygA="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/tenaga-dalam.webp",
    "blur": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoYAA8APp0+mkgloyKhMAgAsBOJZQDLLCHfZR1HUeTADS4AAP766upYuzuD0NdFjHAjFMTMhY3kpbzD/BeGsBQM6YkVGQRBPGpm1EeQMNUsAnkLeOqy27raFP5eq4p8avdizKyP3T4Gezl0ygA="
  },
  {
    "id": "medusa-3d",
    "name": "Medusae",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "3d",
    "color": "#c084fc",
    "description": "Procedural abyss aquarium — every 32-bit seed births a new jellyfish species: bell shape, tentacles, pulse, bioluminescent glow and a generated Latin name.",
    "tech": [
      "React Three Fiber",
      "GLSL",
      "Web Audio"
    ],
    "stats": [],
    "url": "https://medusa-3d.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/medusa-3d.webp",
        "label": "Medusae",
        "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAwAwCdASoYAA8APzmGuVQvKSWjMAgB4CcJQAALfX2EvvgAAP7oz7OmrA7rD1E6FQkmD9uGZM5M9LAbR5e5Y/sn2XgAAA=="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/medusa-3d.webp",
    "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAwAwCdASoYAA8APzmGuVQvKSWjMAgB4CcJQAALfX2EvvgAAP7oz7OmrA7rD1E6FQkmD9uGZM5M9LAbR5e5Y/sn2XgAAA=="
  },
  {
    "id": "kiln-3d",
    "name": "Kiln",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "3d",
    "color": "#b5342e",
    "description": "A potter's wheel — drag the spinning clay to throw a vessel, fire it at 1300°C, then pick a glaze. Every pot is yours.",
    "tech": [
      "React Three Fiber",
      "Lathe Geometry",
      "Web Audio"
    ],
    "stats": [],
    "url": "https://kiln-3d.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/kiln-3d.webp",
        "label": "Kiln",
        "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoYAA8APu1iqU2ppaOiMAgBMB2JYwAAW+k7NujXeGmQAP7wv4a4xhH3AXLOKiHHpt03fVBH8ej5JAqZ95kXXZAA"
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/kiln-3d.webp",
    "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoYAA8APu1iqU2ppaOiMAgBMB2JYwAAW+k7NujXeGmQAP7wv4a4xhH3AXLOKiHHpt03fVBH8ej5JAqZ95kXXZAA"
  },
  {
    "id": "orrery-3d",
    "name": "Orrery",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "3d",
    "color": "#e0a83c",
    "description": "A clockwork solar system driven by real JPL orbital elements — scrub three centuries and the planets go where they actually were.",
    "tech": [
      "React Three Fiber",
      "Keplerian Orbits",
      "Procedural Geometry"
    ],
    "stats": [],
    "url": "https://orrery-3d.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/orrery-3d.webp",
        "label": "Orrery",
        "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAwCdASoYAA8APu1iqU2ppaOiMAgBMB2JZwDKACHf3kHLvVpAAP7yoNfKTICa1vqi5a0abSzCsFwsPBczvz7ADMUlj8rT5byCRJE/AAA="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/orrery-3d.webp",
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAwCdASoYAA8APu1iqU2ppaOiMAgBMB2JZwDKACHf3kHLvVpAAP7yoNfKTICa1vqi5a0abSzCsFwsPBczvz7ADMUlj8rT5byCRJE/AAA="
  },
  {
    "id": "keycraft-3d",
    "name": "Keycraft",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "3d",
    "color": "#ff2e88",
    "description": "Interactive 3D mechanical keyboard you can type on with your own keyboard — procedural keycaps, synthesised switch sounds, six colorways.",
    "tech": [
      "React Three Fiber",
      "Web Audio",
      "Procedural Geometry"
    ],
    "stats": [],
    "url": "https://keycraft-3d.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/keycraft-3d.webp",
        "label": "Keycraft",
        "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoYAA8APu1oqk6ppiQiMAgBMB2JQBdgBDud4YFCAVihbQAA/uvyfoQdDQsmRT1YorLESXHAoPjixor8E6r1dmewBo3iPC6RmszvqDFADdQpyewPI4TFBPi12PvTcAAAAAA="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/keycraft-3d.webp",
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoYAA8APu1oqk6ppiQiMAgBMB2JQBdgBDud4YFCAVihbQAA/uvyfoQdDQsmRT1YorLESXHAoPjixor8E6r1dmewBo3iPC6RmszvqDFADdQpyewPI4TFBPi12PvTcAAAAAA="
  },
  {
    "id": "infinite-dream-world",
    "name": "Infinite Dream World",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "3d",
    "color": "#a78bfa",
    "description": "Cinematic scroll-driven 3D dream world — floating islands, custom GLSL sky & aurora, generative Web Audio soundscape.",
    "tech": [
      "React Three Fiber",
      "GLSL",
      "Web Audio"
    ],
    "stats": [],
    "url": "https://infinite-dream-world.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/infinite-dream-world.webp",
        "label": "Infinite Dream World",
        "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACQAwCdASoYAA8APu1iqk2ppaQiMAgBMB2JaQAAYf/dB5Bgi/t0AP7Um84acpZp2h31YEvBDBDzsfaUae6wAA=="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/infinite-dream-world.webp",
    "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACQAwCdASoYAA8APu1iqk2ppaQiMAgBMB2JaQAAYf/dB5Bgi/t0AP7Um84acpZp2h31YEvBDBDzsfaUae6wAA=="
  },
  {
    "id": "puri-depok-mas-2035",
    "name": "Puri Depok Mas 2035",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "3d",
    "color": "#fb923c",
    "description": "Interactive 3D digital twin of a future Depok neighborhood — scroll flight through 8 scenes with live time-of-day & weather.",
    "tech": [
      "React Three Fiber",
      "drei",
      "TypeScript"
    ],
    "stats": [],
    "url": "https://puri-depok-mas-2035.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/puri-depok-mas-2035.webp",
        "label": "Puri Depok Mas 2035",
        "blur": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAgCdASoYAA8APu1iqU2ppaOiMAgBMB2JZwAAhAwAAP7w2bEEsSRcvtbaKDBhIQlDUIAA"
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/puri-depok-mas-2035.webp",
    "blur": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAgCdASoYAA8APu1iqU2ppaOiMAgBMB2JZwAAhAwAAP7w2bEEsSRcvtbaKDBhIQlDUIAA"
  },
  {
    "id": "ghaisan-3d-site",
    "name": "GRS — Personal 3D Journey",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "3d",
    "color": "#6366f1",
    "description": "Personal-brand 3D site — particle globe hero, interactive roadmap of competitions, organizations and digital projects.",
    "tech": [
      "Next.js",
      "Three.js",
      "TailwindCSS"
    ],
    "stats": [],
    "url": "https://ghaisansyams.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/ghaisan-portfolio.webp",
        "label": "GRS — Personal 3D Journey",
        "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAgCdASoYAA8ALrV2u12jqampiYC0SygABc7E5JbHgAD++RODc8B242MZJgr9Gueqn/NiX8cAAA=="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/ghaisan-portfolio.webp",
    "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAgCdASoYAA8ALrV2u12jqampiYC0SygABc7E5JbHgAD++RODc8B242MZJgr9Gueqn/NiX8cAAA=="
  },
  {
    "id": "threejs-mini-project",
    "name": "Three.js Playground",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "3d",
    "color": "#4ade80",
    "description": "Three.js fundamentals playground — primitives, materials, lighting and orbit controls.",
    "tech": [
      "Three.js",
      "Vite"
    ],
    "stats": [],
    "url": "https://threejs-mini-project.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/threejs-mini-project.webp",
        "label": "Three.js Playground",
        "blur": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAABQAgCdASoYAA8AA4BaJZwDCgEO/cdJd+b9xAAA/vhJCR51j2RShIBiNA2RycY56AAAAA=="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/threejs-mini-project.webp",
    "blur": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAABQAgCdASoYAA8AA4BaJZwDCgEO/cdJd+b9xAAA/vhJCR51j2RShIBiNA2RycY56AAAAA=="
  },
  {
    "id": "cats-cradle",
    "name": "Cat's Cradle",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "3d",
    "color": "#22d3ee",
    "description": "Hand-tracked neon string play — raise both hands to the camera and pluck glowing strings with your fingertips.",
    "tech": [
      "MediaPipe",
      "Canvas",
      "Vanilla JS"
    ],
    "stats": [],
    "url": "https://cats-cradle-nine.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/cats-cradle.webp",
        "label": "Cat's Cradle",
        "blur": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADwAgCdASoYAA8APu1iqU2ppaQiMAgBMB2JZwCw7C0kAAD+8K8lll8D4gA="
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/cats-cradle.webp",
    "blur": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADwAgCdASoYAA8APu1iqU2ppaQiMAgBMB2JZwCw7C0kAAD+8K8lll8D4gA="
  },
  {
    "id": "threejs-runner-game",
    "name": "3D Runner",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "games",
    "color": "#facc15",
    "description": "Endless 3D runner — dodge obstacles at increasing speed, built with vanilla Three.js in one HTML file.",
    "tech": [
      "Three.js",
      "Vanilla JS"
    ],
    "stats": [],
    "url": "https://threejs-runner-game.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/threejs-runner-game.webp",
        "label": "3D Runner",
        "blur": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAwAwCdASoYAA8APu1kqk4ppaQiMAgBMB2JZQAAg+9zK2AAAP7wXGiTZuhSwoQCRNmyCgAA"
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/threejs-runner-game.webp",
    "blur": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAwAwCdASoYAA8APu1kqk4ppaQiMAgBMB2JZQAAg+9zK2AAAP7wXGiTZuhSwoQCRNmyCgAA"
  },
  {
    "id": "threejs-worldcup-penalty",
    "name": "World Cup Penalty",
    "kind": "more",
    "tagline": "",
    "meta": "",
    "category": "games",
    "color": "#34d399",
    "description": "3D penalty-shootout game — aim, power and a goalkeeper that reads your shots.",
    "tech": [
      "Three.js",
      "Vanilla JS"
    ],
    "stats": [],
    "url": "https://threejs-worldcup-penalty.vercel.app",
    "isPrivate": false,
    "shots": [
      {
        "src": "https://ghaisansyams.vercel.app/more/threejs-worldcup-penalty.webp",
        "label": "World Cup Penalty",
        "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQBACdASoYAA8APu1kqU4ppaOiMAgBMB2JZgCdMoADTq+HB+i31ZZZgAD+8L1KZc1ItbaC3MFWUHTMr1eVsOtS+0lKZYXy60r2HegA"
      }
    ],
    "image": "https://ghaisansyams.vercel.app/more/threejs-worldcup-penalty.webp",
    "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQBACdASoYAA8APu1kqU4ppaOiMAgBMB2JZgCdMoADTq+HB+i31ZZZgAD+8L1KZc1ItbaC3MFWUHTMr1eVsOtS+0lKZYXy60r2HegA"
  }
]
